// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onDisplayTextChange();
void onDeployFloatChange();
void onLedChange();
void onReadFloatDataChange();
void onRecordDataChange();

String displayText;
float altitude;
float depth;
float pressure;
float temp;
bool deployFloat;
bool led;
bool readFloatData;
bool recordData;

void initProperties(){

  ArduinoCloud.addProperty(displayText, READWRITE, ON_CHANGE, onDisplayTextChange);
  ArduinoCloud.addProperty(altitude, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(depth, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(pressure, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(deployFloat, READWRITE, ON_CHANGE, onDeployFloatChange);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);
  ArduinoCloud.addProperty(readFloatData, READWRITE, ON_CHANGE, onReadFloatDataChange);
  ArduinoCloud.addProperty(recordData, READWRITE, ON_CHANGE, onRecordDataChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
